-- =====================================================
-- PRIMER PROYECTO: Sistema Reservas Viajes Terrestres
-- ESTUDIANTES: 
--              NESTOR LEIVA
--              RODRIGO ELIAS
-- =====================================================

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'SISTEMA_RESERVA_VIAJES')
    BEGIN 
        CREATE DATABASE SISTEMA_RESERVA_VIAJES;
    END
GO

USE SISTEMA_RESERVA_VIAJES;
GO


-- 1. CATÁLOGOS BÁSICOS
CREATE TABLE ZONA (
    PK_ID_ZONA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_ZONA VARCHAR(30) NOT NULL
);

CREATE TABLE CIUDAD (
    PK_ID_CIUDAD INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_CIUDAD VARCHAR(60) NOT NULL,
    FK_ZONA INT NOT NULL,
    FOREIGN KEY (FK_ZONA) REFERENCES ZONA(PK_ID_ZONA)
);

CREATE TABLE PROFESION (
    PK_ID_PROFESION INT PRIMARY KEY IDENTITY(1,1),
    DETALLE VARCHAR(50) NOT NULL
);

CREATE TABLE EMPRESA_CLIENTE (
    PK_ID_EMPRESA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(80) NOT NULL,
    TELEFONO VARCHAR(16),
    CORREO VARCHAR(100),
    DIRECCION VARCHAR(120)
);

CREATE TABLE RANGO_SALARIAL (
    PK_ID_RANGO INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(50) NOT NULL,
    SALARIO_MIN DECIMAL(10,2),
    SALARIO_MAX DECIMAL(10,2)
);

-- 2. PERSONAS
CREATE TABLE CLIENTE (
    PK_ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
    CEDULA VARCHAR(20) UNIQUE NOT NULL,
    NOMBRE_COMPLETO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(16),
    CORREO VARCHAR(100),
    FK_PROFESION INT NOT NULL,
    FK_EMPRESA INT,
    FK_RANGO INT NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    FOREIGN KEY (FK_PROFESION) REFERENCES PROFESION(PK_ID_PROFESION),
    FOREIGN KEY (FK_EMPRESA) REFERENCES EMPRESA_CLIENTE(PK_ID_EMPRESA),
    FOREIGN KEY (FK_RANGO) REFERENCES RANGO_SALARIAL(PK_ID_RANGO)
);

CREATE TABLE ROL_EMPLEADO (
    PK_ID_ROL INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_ROL VARCHAR(30) NOT NULL
);

CREATE TABLE EMPLEADO (
    PK_ID_EMPLEADO INT PRIMARY KEY IDENTITY(1,1),
    CEDULA VARCHAR(20) UNIQUE NOT NULL,
    NOMBRE_COMPLETO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(16),
    CORREO VARCHAR(100),
    FK_ROL INT NOT NULL,
    ACTIVO BIT NOT NULL, -- SQL Server usa BIT en vez de BOOLEAN
    FOREIGN KEY (FK_ROL) REFERENCES ROL_EMPLEADO(PK_ID_ROL)
);

-- 3. RUTAS
CREATE TABLE RUTA (
    PK_ID_RUTA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_RUTA VARCHAR(80) NOT NULL,
    FK_CIUDAD_ORIGEN INT NOT NULL,
    FK_CIUDAD_DESTINO INT NOT NULL,
    DURACION_ESTIMADA_MIN INT,
    FOREIGN KEY (FK_CIUDAD_ORIGEN) REFERENCES CIUDAD(PK_ID_CIUDAD),
    FOREIGN KEY (FK_CIUDAD_DESTINO) REFERENCES CIUDAD(PK_ID_CIUDAD)
);

-- 4. VEHÍCULOS
CREATE TABLE TIPO_AUTOBUS (
    PK_ID_TIPO INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(40) NOT NULL
);

CREATE TABLE AUTOBUS (
    PK_ID_AUTOBUS INT PRIMARY KEY IDENTITY(1,1),
    PLACA VARCHAR(10) UNIQUE NOT NULL,
    CAPACIDAD_ASIENTOS INT NOT NULL,
    FK_TIPO_AUTOBUS INT NOT NULL,
    ANNO_FABRICACION INT,
    ACTIVO BIT NOT NULL,
    FOREIGN KEY (FK_TIPO_AUTOBUS) REFERENCES TIPO_AUTOBUS(PK_ID_TIPO)
);

CREATE TABLE DEKRA (
    PK_ID_DEKRA INT PRIMARY KEY IDENTITY(1,1),
    FK_AUTOBUS INT NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    RESULTADO VARCHAR(20) NOT NULL,
    OBSERVACIONES VARCHAR(200),
    FOREIGN KEY (FK_AUTOBUS) REFERENCES AUTOBUS(PK_ID_AUTOBUS)
);

CREATE TABLE MARCHAMO (
    PK_ID_MARCHAMO INT PRIMARY KEY IDENTITY(1,1),
    FK_AUTOBUS INT NOT NULL,
    ANNO INT NOT NULL,
    FECHA_PAGO DATE NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_AUTOBUS) REFERENCES AUTOBUS(PK_ID_AUTOBUS)
);

-- 5. VIAJES Y RESERVAS
CREATE TABLE VIAJE_PROGRAMADO (
    PK_ID_VIAJE INT PRIMARY KEY IDENTITY(1,1),
    FK_RUTA INT NOT NULL,
    FK_AUTOBUS INT NOT NULL,
    FK_CHOFER INT NOT NULL,
    FK_FISCAL INT NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    HORA_SALIDA TIME NOT NULL,
    TARIFA_BASE DECIMAL(10,2) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_RUTA) REFERENCES RUTA(PK_ID_RUTA),
    FOREIGN KEY (FK_AUTOBUS) REFERENCES AUTOBUS(PK_ID_AUTOBUS),
    FOREIGN KEY (FK_CHOFER) REFERENCES EMPLEADO(PK_ID_EMPLEADO),
    FOREIGN KEY (FK_FISCAL) REFERENCES EMPLEADO(PK_ID_EMPLEADO)
);

CREATE TABLE RESERVACION (
    PK_ID_RESERVACION INT PRIMARY KEY IDENTITY(1,1),
    FK_CLIENTE INT NOT NULL,
    FK_VIAJE INT NOT NULL,
    FK_ADMINISTRATIVO INT NOT NULL,
    FECHA_RESERVA DATE NOT NULL,
    HORA_RESERVA TIME NOT NULL,
    CANTIDAD_ASIENTOS INT NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(PK_ID_CLIENTE),
    FOREIGN KEY (FK_VIAJE) REFERENCES VIAJE_PROGRAMADO(PK_ID_VIAJE),
    FOREIGN KEY (FK_ADMINISTRATIVO) REFERENCES EMPLEADO(PK_ID_EMPLEADO)
);

CREATE TABLE DETALLE_RESERVACION (
    PK_ID_DETALLE INT PRIMARY KEY IDENTITY(1,1),
    FK_RESERVACION INT NOT NULL,
    NUMERO_ASIENTO INT NOT NULL,
    FOREIGN KEY (FK_RESERVACION) REFERENCES RESERVACION(PK_ID_RESERVACION)
);

-- 6. FACTURACIÓN
CREATE TABLE METODO_PAGO (
    PK_ID_METODO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_METODO VARCHAR(40) NOT NULL
);

CREATE TABLE FACTURA (
    PK_ID_FACTURA INT PRIMARY KEY IDENTITY(1,1),
    NUMERO_FACTURA VARCHAR(20) UNIQUE NOT NULL,
    FK_RESERVACION INT NOT NULL,
    FK_METODO_PAGO INT NOT NULL,
    FECHA_FACTURA DATE NOT NULL,
    MONTO_TOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (FK_RESERVACION) REFERENCES RESERVACION(PK_ID_RESERVACION),
    FOREIGN KEY (FK_METODO_PAGO) REFERENCES METODO_PAGO(PK_ID_METODO)
);

CREATE TABLE DETALLE_FACTURA (
    PK_ID_DETALLE_FACT INT PRIMARY KEY IDENTITY(1,1),
    FK_FACTURA INT NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (FK_FACTURA) REFERENCES FACTURA(PK_ID_FACTURA)
);

-- 7. MANTENIMIENTO
CREATE TABLE TIPO_MANTENIMIENTO (
    PK_ID_TIPO_MANT INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE MANTENIMIENTO_AUTOBUS (
    PK_ID_MANTENIMIENTO INT PRIMARY KEY IDENTITY(1,1),
    FK_AUTOBUS INT NOT NULL,
    FK_TIPO_MANTENIMIENTO INT NOT NULL,
    FECHA_MANTENIMIENTO DATE NOT NULL,
    COSTO DECIMAL(10,2),
    DESCRIPCION_TRABAJO VARCHAR(200),
    FOREIGN KEY (FK_AUTOBUS) REFERENCES AUTOBUS(PK_ID_AUTOBUS),
    FOREIGN KEY (FK_TIPO_MANTENIMIENTO) REFERENCES TIPO_MANTENIMIENTO(PK_ID_TIPO_MANT)
);

-- 8. BITÁCORA
CREATE TABLE USUARIO_SISTEMA (
    PK_ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_USUARIO VARCHAR(40) UNIQUE NOT NULL,
    CLAVE_HASH VARCHAR(200) NOT NULL,
    FK_EMPLEADO INT NOT NULL,
    FOREIGN KEY (FK_EMPLEADO) REFERENCES EMPLEADO(PK_ID_EMPLEADO)
);

CREATE TABLE BITACORA_ACCESOS (
    PK_ID_BITACORA INT PRIMARY KEY IDENTITY(1,1),
    FK_USUARIO INT NOT NULL,
    FECHA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACCION VARCHAR(100) NOT NULL,
    IP_CLIENTE VARCHAR(45),
    FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO_SISTEMA(PK_ID_USUARIO)
);